
cloud:
  aws:
    credentials:
      access-key: AKIAUJKFKLA2JIVFNNNL
      secret-key: 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
    region:
      static: ap-northeast-1
    stack:
      auto: false

application:
  bucket:
    name: buildinghasan
