POST http://localhost:8081/attach/upload/profile
Content-Type: multipart/form-data; boundary=WebAppBoundary
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NzA2NjY4OTksImV4cCI6MTY3MDc1MzI5OSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxfQ.cZGxCm71OlIxefNCKkd9lRYtl-JmI10ng7mlo03pQ3U

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="download.jfif"

< C:\Users\hasan\OneDrive\Desktop\download.jfif

###
GET http://localhost:8081/attach/open?fileId=8a8a83d184f61a080184f61cd3480000

###
GET http://localhost:8081/attach/open/8a8a833984fb7bbb0184fb85330e0000

###

DELETE http://localhost:8081/attach/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NzA2NjY4OTksImV4cCI6MTY3MDc1MzI5OSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxfQ.cZGxCm71OlIxefNCKkd9lRYtl-JmI10ng7mlo03pQ3U

###

GET http://localhost:8081/attach/pagination?page=0&size=2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NzA2NjY4OTksImV4cCI6MTY3MDc1MzI5OSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxfQ.cZGxCm71OlIxefNCKkd9lRYtl-JmI10ng7mlo03pQ3U
