GET localhost:8081/home/public/pagination?page=0&size=5

###

POST http://localhost:8081/home/comp/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NzA3NDc3NTYsImV4cCI6MTY3MDgzNDE1NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxfQ.WqynwlTGFojKqN_MvsXTAm-_QPmA0kCBwuzWLFlPtAk

{
  "paymentTypesId" : [{"defaultCash":23,
                       "paymentTerm":23.3,
                       "paymentCash":21.21,
                       "duration":12},
                       {"defaultCash":230,
                        "paymentTerm":21.3,
                        "paymentCash":2.21,
                        "duration":18}],
  "attachesId" : ["8a8a833984fb89e60184fb90f4690000","8a8a83d184f61a080184f61cd3480000"],
  "content": "sdadasadasdasdasdadadsadadasd dssdsd sd  sd ssd s",
  "phoneNumber": "+99043123456",
  "area": 54,
  "summa": 33000,
  "countRoom": 2,
  "floor": 4,
  "totalFloor": 9,
  "buildStatus": "LEVEL3"
}

###
DELETE http://localhost:8081/home/comp?id=8a8a83398500530501850054ea020001
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NzA3NDc3NTYsImV4cCI6MTY3MDgzNDE1NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxfQ.WqynwlTGFojKqN_MvsXTAm-_QPmA0kCBwuzWLFlPtAk
